import type { Deal } from '@/types/deal';

export const MOCK_DEALS: Deal[] = [
  {
    id: 'ppomppu-mock-1',
    title: '[삼성] 갤럭시 버즈3 프로 정품 역대급 특가',
    productName: '갤럭시 버즈3 프로 정품 역대급 특가',
    url: 'https://www.ppomppu.co.kr',
    price: '89,000원',
    originalPrice: '149,000원',
    discountRate: '-40%',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'electronics',
    commentCount: 234, likeCount: 891,
    publishedAt: new Date(Date.now() - 30 * 60e3).toISOString(),
    description: '삼성 공홈 기준 149,000원인데 역대 최저가 경신',
  },
  {
    id: 'ppomppu-mock-2',
    title: '애플 에어팟 프로 2세대 USB-C 세일',
    productName: '애플 에어팟 프로 2세대 USB-C 세일',
    url: 'https://www.ppomppu.co.kr',
    price: '199,000원',
    originalPrice: '329,000원',
    discountRate: '-39%',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'electronics',
    commentCount: 178, likeCount: 654,
    publishedAt: new Date(Date.now() - 1.5 * 36e5).toISOString(),
  },
  {
    id: 'ppomppu-mock-3',
    title: 'PS5 슬림 디스크 에디션 + 게임 2종 번들 핫딜',
    productName: 'PS5 슬림 디스크 에디션 + 게임 2종 번들 핫딜',
    url: 'https://www.ppomppu.co.kr',
    price: '549,000원',
    originalPrice: '699,000원',
    discountRate: '-21%',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'game',
    commentCount: 312, likeCount: 1024,
    publishedAt: new Date(Date.now() - 45 * 60e3).toISOString(),
  },
  {
    id: 'ppomppu-mock-4',
    title: '[BBQ] 황금올리브치킨 + 콜라 2L 세트 반값 할인',
    productName: '황금올리브치킨 + 콜라 2L 세트 반값 할인',
    url: 'https://www.ppomppu.co.kr',
    price: '12,500원',
    originalPrice: '25,000원',
    discountRate: '-50%',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'food',
    commentCount: 456, likeCount: 1200,
    publishedAt: new Date(Date.now() - 20 * 60e3).toISOString(),
  },
  {
    id: 'ppomppu-mock-5',
    title: '나이키 에어맥스 90 봄 시즌 한정 세일',
    productName: '나이키 에어맥스 90 봄 시즌 한정 세일',
    url: 'https://www.ppomppu.co.kr',
    price: '79,000원',
    originalPrice: '149,000원',
    discountRate: '-47%',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'fashion',
    commentCount: 89, likeCount: 320,
    publishedAt: new Date(Date.now() - 2.5 * 36e5).toISOString(),
  },
  {
    id: 'ppomppu-mock-6',
    title: '샤오미 로봇청소기 S10+ 국내정품 최저가',
    productName: '샤오미 로봇청소기 S10+ 국내정품 최저가',
    url: 'https://www.ppomppu.co.kr',
    price: '289,000원',
    originalPrice: '499,000원',
    discountRate: '-42%',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'living',
    commentCount: 145, likeCount: 567,
    publishedAt: new Date(Date.now() - 3 * 36e5).toISOString(),
  },
  {
    id: 'ppomppu-mock-7',
    title: '닌텐도 스위치 OLED 젤다의 전설 에디션',
    productName: '닌텐도 스위치 OLED 젤다의 전설 에디션',
    url: 'https://www.ppomppu.co.kr',
    price: '399,000원',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'game',
    commentCount: 201, likeCount: 789,
    publishedAt: new Date(Date.now() - 4 * 36e5).toISOString(),
  },
  {
    id: 'ppomppu-mock-8',
    title: '[쿠팡] 비비고 왕교자 1.4kg x 3봉 무료배송',
    productName: '비비고 왕교자 1.4kg x 3봉 무료배송',
    url: 'https://www.ppomppu.co.kr',
    price: '18,900원',
    originalPrice: '28,500원',
    discountRate: '-34%',
    source: 'ppomppu', sourceName: '뽐뿌', category: 'food',
    commentCount: 167, likeCount: 445,
    publishedAt: new Date(Date.now() - 5 * 36e5).toISOString(),
  },
];
