-- Create the price_history table
CREATE TABLE IF NOT EXISTS public.price_history (
    id bigint generated by default as identity primary key,
    match_key text not null,
    price_value integer not null,
    price_str text not null,
    source text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster historical queries by match_key
CREATE INDEX IF NOT EXISTS idx_price_history_match_key ON public.price_history (match_key);

-- Set up Row Level Security (RLS)
ALTER TABLE public.price_history ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts (since we use anon key to insert)
CREATE POLICY "Allow anonymous inserts" ON public.price_history
    FOR INSERT WITH CHECK (true);

-- Create policy to allow anonymous selects
CREATE POLICY "Allow anonymous selects" ON public.price_history
    FOR SELECT USING (true);
